routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['get.menu']], function () {
    //Route::get('/', 'HomeController@index')->middleware('auth');
    Route::get('/', 'HomeController@index');
    Route::get('home/{id}', 'HomeController@show');

    Route::post('city-dropdown', 'DirektoriController@getdistrict')->name('city-dropdown');

    //Route::get('/', function () {           return view('dashboard.homepage'); });

    Route::group(['middleware' => ['role:user']], function () {
        Route::get('/colors', function () {     return view('dashboard.colors'); });
        Route::get('/typography', function () { return view('dashboard.typography'); });
        Route::get('/charts', function () {     return view('dashboard.charts'); });
        Route::get('/widgets', function () {    return view('dashboard.widgets'); });
        Route::get('/404', function () {        return view('dashboard.404'); });
        Route::get('/500', function () {        return view('dashboard.500'); });
        Route::prefix('base')->group(function () {  
            Route::get('/breadcrumb', function(){   return view('dashboard.base.breadcrumb'); });
            Route::get('/cards', function(){        return view('dashboard.base.cards'); });
            Route::get('/carousel', function(){     return view('dashboard.base.carousel'); });
            Route::get('/collapse', function(){     return view('dashboard.base.collapse'); });

            Route::get('/forms', function(){        return view('dashboard.base.forms'); });
            Route::get('/jumbotron', function(){    return view('dashboard.base.jumbotron'); });
            Route::get('/list-group', function(){   return view('dashboard.base.list-group'); });
            Route::get('/navs', function(){         return view('dashboard.base.navs'); });

            Route::get('/pagination', function(){   return view('dashboard.base.pagination'); });
            Route::get('/popovers', function(){     return view('dashboard.base.popovers'); });
            Route::get('/progress', function(){     return view('dashboard.base.progress'); });
            Route::get('/scrollspy', function(){    return view('dashboard.base.scrollspy'); });

            Route::get('/switches', function(){     return view('dashboard.base.switches'); });
            Route::get('/tables', function () {     return view('dashboard.base.tables'); });
            Route::get('/tabs', function () {       return view('dashboard.base.tabs'); });
            Route::get('/tooltips', function () {   return view('dashboard.base.tooltips'); });
        });
        Route::prefix('buttons')->group(function () {  
            Route::get('/buttons', function(){          return view('dashboard.buttons.buttons'); });
            Route::get('/button-group', function(){     return view('dashboard.buttons.button-group'); });
            Route::get('/dropdowns', function(){        return view('dashboard.buttons.dropdowns'); });
            Route::get('/brand-buttons', function(){    return view('dashboard.buttons.brand-buttons'); });
        });
        Route::prefix('icon')->group(function () {  // word: "icons" - not working as part of adress
            Route::get('/coreui-icons', function(){         return view('dashboard.icons.coreui-icons'); });
            Route::get('/flags', function(){                return view('dashboard.icons.flags'); });
            Route::get('/brands', function(){               return view('dashboard.icons.brands'); });
        });
        Route::prefix('notifications')->group(function () {  
            Route::get('/alerts', function(){   return view('dashboard.notifications.alerts'); });
            Route::get('/badge', function(){    return view('dashboard.notifications.badge'); });
            Route::get('/modals', function(){   return view('dashboard.notifications.modals'); });
        });
        Route::resource('notes', 'NotesController');
        Route::resource('pelaku', 'PelakuUsahaController');
        Route::resource('direktori', 'DirektoriController');
    });
    Auth::routes();

    Route::resource('resource/{table}/resource', 'ResourceController')->names([
        'index'     => 'resource.index',
        'create'    => 'resource.create',
        'store'     => 'resource.store',
        'show'      => 'resource.show',
        'edit'      => 'resource.edit',
        'update'    => 'resource.update',
        'destroy'   => 'resource.destroy'
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
        Route::resource('bread',  'BreadController');   //create BREAD (resource)
        Route::resource('users',        'UsersController') ;
        Route::resource('roles',        'RolesController');
        Route::resource('mail',        'MailController');
        Route::get('prepareSend/{id}',        'MailController@prepareSend')->name('prepareSend');
        Route::post('mailSend/{id}',        'MailController@send')->name('mailSend');
        Route::get('/roles/move/move-up',      'RolesController@moveUp')->name('roles.up');
        Route::get('/roles/move/move-down',    'RolesController@moveDown')->name('roles.down');
        Route::prefix('menu/element')->group(function () { 
            Route::get('/',             'MenuElementController@index')->name('menu.index');
            Route::get('/move-up',      'MenuElementController@moveUp')->name('menu.up');
            Route::get('/move-down',    'MenuElementController@moveDown')->name('menu.down');
            Route::get('/create',       'MenuElementController@create')->name('menu.create');
            Route::post('/store',       'MenuElementController@store')->name('menu.store');
            Route::get('/get-parents',  'MenuElementController@getParents');
            Route::get('/edit',         'MenuElementController@edit')->name('menu.edit');
            Route::post('/update',      'MenuElementController@update')->name('menu.update');
            Route::get('/show',         'MenuElementController@show')->name('menu.show');
            Route::get('/delete',       'MenuElementController@delete')->name('menu.delete');
        });
        Route::prefix('menu/menu')->group(function () { 
            Route::get('/',         'MenuController@index')->name('menu.menu.index');
            Route::get('/create',   'MenuController@create')->name('menu.menu.create');
            Route::post('/store',   'MenuController@store')->name('menu.menu.store');
            Route::get('/edit',     'MenuController@edit')->name('menu.menu.edit');
            Route::post('/update',  'MenuController@update')->name('menu.menu.update');
            Route::get('/delete',   'MenuController@delete')->name('menu.menu.delete');
        });
        Route::prefix('media')->group(function () {
            Route::get('/',                 'MediaController@index')->name('media.folder.index');
            Route::get('/folder/store',     'MediaController@folderAdd')->name('media.folder.add');
            Route::post('/folder/update',   'MediaController@folderUpdate')->name('media.folder.update');
            Route::get('/folder',           'MediaController@folder')->name('media.folder');
            Route::post('/folder/move',     'MediaController@folderMove')->name('media.folder.move');
            Route::post('/folder/delete',   'MediaController@folderDelete')->name('media.folder.delete');;

            Route::post('/file/store',      'MediaController@fileAdd')->name('media.file.add');
            Route::get('/file',             'MediaController@file');
            Route::post('/file/delete',     'MediaController@fileDelete')->name('media.file.delete');
            Route::post('/file/update',     'MediaController@fileUpdate')->name('media.file.update');
            Route::post('/file/move',       'MediaController@fileMove')->name('media.file.move');
            Route::post('/file/cropp',      'MediaController@cropp');
            Route::get('/file/copy',        'MediaController@fileCopy')->name('media.file.copy');
        });
    });
});

app/Models/Direktori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Direktori extends Model
{

    use HasFactory;

    protected $table = 'direktori';

    /**
     * Get the User that owns the Notes.
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'users_id')->withTrashed();
    }

    /**
     * Get the Status that owns the Notes.
     */
    public function status()
    {
        return $this->belongsTo('App\Models\PelakuUsaha', 'pelaku_usaha_id');
    }

    public function province()
    {
        return $this->belongsTo('App\Models\Province', 'province_id');
    }

    public function district()
    {
        return $this->belongsTo('App\Models\District', 'district_id');
    }
}

app/Http/Controllers/DirektoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Direktori;
use App\Models\PelakuUsaha;
use App\Models\Province;
use App\Models\District;

class DirektoriController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notes = Direktori::with('user')->with('status')->paginate( 20 );
        return view('dashboard.direktori.direktoriList', ['notes' => $notes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pelaku = PelakuUsaha::all();
        $province = Province::all();
        return view('dashboard.direktori.create', [ 'pelaku' => $pelaku, 'province' => $province ]);
    }

    public function getdistrict(Request $request)
    {
        $cities = District::where('province_id', $request->get('id'))
            ->pluck('name', 'id');
    
        return response()->json($cities);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama'             => 'required|min:1|max:64',
            'pelaku_usaha_id'   => 'required'
        ]);
        $user = auth()->user();
        $note = new Direktori();
        $note->nama     = $request->input('nama');
        $note->no_hp   = $request->input('no_hp');
        $note->pelaku_usaha_id = $request->input('pelaku_usaha_id');
        $note->province_id = $request->input('province_id');
        $note->district_id = $request->input('district_id');
        $note->alamat = $request->input('alamat');
        $note->sumber = $request->input('sumber');
        $note->komoditas = $request->input('komoditas');
        $note->users_id = $user->id;
        $note->save();
        $request->session()->flash('message', 'Successfully created Direktori');
        return redirect()->route('direktori.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $note = Direktori::with('user')->with('status')->with('province')->with('district')->find($id);
        return view('dashboard.direktori.direktoriShow', [ 'note' => $note ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $note = Direktori::find($id);
        $pelaku = PelakuUsaha::all();
        $province = Province::all();
        $district = District::all();
        return view('dashboard.direktori.edit', [ 'pelaku' => $pelaku, 'note' => $note, 'province' => $province, 'district' => $district ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //die();
        $validatedData = $request->validate([
            'nama'             => 'required|min:1|max:64',
            'pelaku_usaha_id'   => 'required'
        ]);
        $note = Direktori::find($id);
        $note->nama     = $request->input('nama');
        $note->no_hp   = $request->input('no_hp');
        $note->pelaku_usaha_id = $request->input('pelaku_usaha_id');
        $note->alamat = $request->input('alamat');
        $note->sumber = $request->input('sumber');
        $note->komoditas = $request->input('komoditas');
        $note->province_id = $request->input('province_id');
        $note->district_id = $request->input('district_id');
        $note->save();
        $request->session()->flash('message', 'Successfully edited direktori');
        return redirect()->route('direktori.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $note = Direktori::find($id);
        if($note){
            $note->delete();
        }
        return redirect()->route('direktori.index');
    }
}

resources/views/dashboard/direktori/create.blade.php
@extends('dashboard.base')

@section('content')

        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> {{ __('Create Direktori') }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('direktori.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label>Nama Pelaku Usaha</label>
                                <input class="form-control" type="text" placeholder="{{ __('Nama') }}" name="nama" required autofocus>
                            </div>

                            <div class="form-group row">
                                <label>Jenis Usaha</label>
                                <select class="form-control" name="pelaku_usaha_id" required autofocus>
                                    @foreach($pelaku as $pelaku)
                                        <option value="{{ $pelaku->id }}">{{ $pelaku->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group row">
                                <label>Provinsi</label>
                                <select class="form-control" name="province_id" id="province" autofocus>
                                    <option value="">==Pilih Provinsi==</option>
                                    @foreach($province as $province)
                                    <option value="{{ $province->id }}">{{ $province->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group row">
                                <label>Kota</label>
                                <select class="form-control" name="district_id" id="district" autofocus>
                                    <option value="">==Pilih Kota==</option>
                                </select>
                            </div>

                            <div class="form-group row">
                                <label>Komoditas Utama</label>
                                <input class="form-control" type="text" placeholder="{{ __('Komoditas') }}" name="komoditas"  autofocus>
                            </div>

                            <div class="form-group row">
                                <label>Alamat</label>
                                <textarea class="form-control" id="textarea-input" name="alamat" rows="9" placeholder="{{ __('Alamat..') }}"></textarea>
                            </div>

                            <div class="form-group row">
                                <label>No Telepon</label>
                                <input class="form-control" type="text" placeholder="{{ __('Telepon') }}" name="no_hp"  autofocus>
                            </div>
                            
                            <div class="form-group row">
                                <label>Sumber</label>
                                <textarea class="form-control" id="textarea-input" name="sumber" rows="9" placeholder="{{ __('Sumber..') }}"></textarea>
                            </div>

                            <button class="btn btn-block btn-success" type="submit">{{ __('Add') }}</button>
                            <a href="{{ route('direktori.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a> 
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection

@section('javascript')
<script>
$(function () {

    $.ajaxSetup({
        headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
    });
    
    $('#province').on('change', function () {
        $.ajax({
            url: '{{ route('city-dropdown') }}',
            method: 'POST',
            data: {id: $(this).val()},
            success: function (response) {
                $('#district').empty();

                $.each(response, function (id, name) {
                    $('#district').append(new Option(name, id))
                })
            }
        })
    });
});
</script>
@endsection

resources/views/dashboard/direktori/direktoriList.blade.php
@extends('dashboard.base')

@section('content')

        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i>{{ __('Direktori Usaha') }}</div>
                    <div class="card-body">
                        <div class="row"> 
                          <a href="{{ route('direktori.create') }}" class="btn btn-primary m-2">{{ __('Add Direktori') }}</a>
                        </div>
                        <br>
                        <table class="table table-responsive-sm table-striped">
                        <thead>
                          <tr>
                            <th>Nama Pelaku Usaha</th>
                            <th>Jenis Usaha</th>
                            <th>Komoditas Utama</th>
                            <th>Alamat</th>
                            <th>Nomor Telepon</th>
                            <th>Sumber</th>
                            <th></th>
                            <th></th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($notes as $note)
                            <tr>
                              <td><strong>{{ $note->nama }}</strong></td>
                              <td><strong>{{ $note->status->name }}</strong></td>
                              <td>{{ $note->komoditas }}</td>
                              <td>{{ $note->alamat }}</td>
                              <td>{{ $note->no_hp }}
                              </td>
                              <td>{{ $note->sumber }}</td>
                              <td>
                                <a href="{{ url('/direktori/' . $note->id) }}" class="btn btn-sm btn-primary"><i class="cil-caret-right"></i></a>
                              </td>
                              <td>
                                <a href="{{ url('/direktori/' . $note->id . '/edit') }}" class="btn btn-sm btn-primary"><i class="cil-pencil"></i></a>
                              </td>
                              <td>
                                <form action="{{ route('direktori.destroy', $note->id ) }}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-sm btn-danger"><i class="cil-trash"></i></button>
                                </form>
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                      {{ $notes->links() }}
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection


@section('javascript')

@endsection

resources/views/dashboard/direktori/direktoriShow.blade.php
@extends('dashboard.base')

@section('content')

               <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> Direktori: {{ $note->nama }}</div>
                    <div class="card-body">
                        <br>
                        <h4>Author:</h4>
                        <p> {{ $note->user->name }}</p>
                        <h4>Nama:</h4>
                        <p> {{ $note->nama }}</p>
                        <h4>Komoditas:</h4> 
                        <p>{{ $note->komoditas }}</p>
                        <h4>Alamat:</h4> 
                        <p>{{ $note->alamat }}</p>
                        <h4> Jenis Usaha: </h4>
                        <p>
                              {{ $note->status->name }}
                        </p>
                        <h4>Sumber:</h4>
                        <p>{{ $note->sumber }}</p>
                        <h4>Kota:</h4> 
                        <p>{{ !empty($note->district) ? $note->district->name:'-' }}</p>
                        <h4>Provinsi:</h4> 
                        <p>{{ $note->province->name }}</p>
                        <a href="{{ route('direktori.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection


@section('javascript')

@endsection

resources/views/dashboard/direktori/edit.blade.php
@extends('dashboard.base')

@section('content')

        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> {{ __('Edit') }}: {{ $note->nama }}</div>
                    <div class="card-body">
                        <form method="POST" action="/direktori/{{ $note->id }}">
                            @csrf
                            @method('PUT')
                            <div class="form-group row">
                                <div class="col">
                                    <label>Nama Pelaku Usaha</label>
                                    <input class="form-control" type="text" placeholder="{{ __('Nama') }}" name="nama" value="{{ $note->nama }}" required autofocus>
                                </div>
                            </div>

                             <div class="form-group row">
                                <div class="col">
                                    <label>Jenis Pelaku Usaha</label>
                                    <select class="form-control" name="pelaku_usaha_id">
                                        @foreach($pelaku as $pelaku)
                                            @if( $pelaku->id == $note->pelaku_usaha_id )
                                                <option value="{{ $pelaku->id }}" selected="true">{{ $pelaku->name }}</option>
                                            @else
                                                <option value="{{ $pelaku->id }}">{{ $pelaku->name }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col">
                                    <label>Provinsi</label>
                                    <select class="form-control" name="province_id" id="province">
                                        @foreach($province as $province)
                                            @if( $province->id == $note->province_id )
                                                <option value="{{ $province->id }}" selected="true">{{ $province->name }}</option>
                                            @else
                                                <option value="{{ $province->id }}">{{ $province->name }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col">
                                    <label>Kota</label>
                                    <select class="form-control" name="district_id" id="district">
                                        @foreach($district as $district)
                                            @if( $district->id == $note->district_id )
                                            <option value="{{ $district->id }}" selected="true">{{ $district->name }}</option>
                                            @endif
                                        @endforeach
                                            <option value="">==Pilih Kota==</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col">
                                    <label>Komoditas Utama</label>
                                    <input class="form-control" type="text" placeholder="{{ __('Komoditas') }}" name="komoditas" value="{{ $note->komoditas }}" autofocus>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col">
                                    <label>Alamat</label>
                                    <textarea class="form-control" id="textarea-input" name="alamat" rows="9" placeholder="{{ __('Alamat..') }}">{{ $note->alamat }}</textarea>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col">
                                    <label>No Telepon</label>
                                    <input class="form-control" type="text" placeholder="{{ __('nohp') }}" name="no_hp" value="{{ $note->no_hp }}" autofocus>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col">
                                    <label>Sumber</label>
                                    <textarea class="form-control" id="textarea-input" name="sumber" rows="9" placeholder="{{ __('Sumber..') }}">{{ $note->sumber }}</textarea>
                                </div>
                            </div>
 
                            <button class="btn btn-block btn-success" type="submit">{{ __('Save') }}</button>
                            <a href="{{ route('direktori.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a> 
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection

@section('javascript')
<script>
$(function () {

    $.ajaxSetup({
        headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
    });
    
    $('#province').on('change', function () {
        $.ajax({
            url: '{{ route('city-dropdown') }}',
            method: 'POST',
            data: {id: $(this).val()},
            success: function (response) {
                $('#district').empty();

                $.each(response, function (id, name) {
                    $('#district').append(new Option(name, id))
                })
            }
        })
    });
});
</script>
@endsection